name: Build

on:
  workflow_dispatch:

  push:
    # Pattern matched against refs/tags
    tags:
      - '**'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.7"
          - os: ubuntu-latest
            python-version: "3.8"
          - os: ubuntu-latest
            python-version: "3.9"
          - os: ubuntu-latest
            python-version: "3.10"
          - os: ubuntu-latest
            python-version: "3.11"
          - os: macos-latest
            python-version: "3.7"
          - os: macos-latest
            python-version: "3.8"
          - os: macos-latest
            python-version: "3.9"
          - os: macos-latest
            python-version: "3.10"
          - os: macos-latest
            python-version: "3.11"
          - os: windows-2019
            python-version: "3.7"
          - os: windows-2019
            python-version: "3.8"
          - os: windows-2019
            python-version: "3.9"
    steps:
      - name: Checkout l0learn
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        run: |
          cd python
          python -m cibuildwheel --output-dir l0learn-wheelhouse
        env:
          CIBW_SKIP: pp* *-win32 *-manylinux_i686 *musllinux*
          CIBW_BUILD: cp${{ matrix.python-version.replace('.', '') }}-*

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: l0learn-wheelhouse
          path: python/l0learn-wheelhouse/




#
#  upload-to-pypip:
#    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
#    name: Publish a Python distribution to PyPI
#    runs-on: ubuntu-latest
#    needs: build_wheels
#
#    steps:
#      - name: Checkout l0learn
#        uses: actions/checkout@v2
#
#      - name: Setup Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.7
#
#      - name: Download l0learn-wheelhouse artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: l0learn-wheelhouse
#          path: python/l0learn-wheelhouse/
#
#      - name: upload-artifact
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_API_TOKEN }}
#          packages_dir: python/l0learn-wheelhouse/

